from collections.abc import Mapping
from decimal import Decimal
from typing import Protocol

from nautilus_trader.config import StrategyConfig
from nautilus_trader.core.nautilus_pyo3 import (
    Bar,
    BarType,
    ClientOrderId,
    Currency,
    InstrumentId,
    Money,
    OrderAccepted,
    OrderCanceled,
    OrderCancelRejected,
    OrderFilled,
    OrderRejected,
    OrderSide,
    OrderType,
    PositionSide,
    Price,
    Quantity,
    TimeInForce,
    TrailingOffsetType,
    TriggerType,
    Venue,
)
from nautilus_trader.model.instruments import Instrument

OrderEvent = OrderAccepted | OrderCancelRejected | OrderCanceled | OrderFilled | OrderRejected

class _Order(Protocol):
    @property
    def client_order_id(self) -> ClientOrderId: ...
    @property
    def instrument_id(self) -> InstrumentId: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def is_reduce_only(self) -> bool: ...
    @property
    def order_type(self) -> OrderType: ...
    @property
    def price(self) -> Price | None: ...
    @property
    def quantity(self) -> Quantity: ...
    @property
    def side(self) -> OrderSide: ...
    @property
    def tags(self) -> list[str] | None: ...
    @property
    def trigger_price(self) -> Price | None: ...
    @property
    def ts_init(self) -> int: ...

class _Position(Protocol):
    @property
    def avg_px_open(self) -> float: ...
    @property
    def instrument_id(self) -> InstrumentId: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def is_long(self) -> bool: ...
    @property
    def is_short(self) -> bool: ...
    @property
    def quantity(self) -> Quantity: ...
    @property
    def side(self) -> PositionSide: ...

class _Balance:
    @property
    def free(self) -> Money: ...

class _Account:
    def balances(self) -> Mapping[Currency, _Balance]: ...

class _Cache:
    def bars(self, bar_type: BarType) -> list[Bar]: ...
    def instrument(self, instrument_id: InstrumentId) -> Instrument | None: ...
    def order(self, client_order_id: ClientOrderId) -> _Order | None: ...
    def orders_open(self, *, instrument_id: InstrumentId | None = ...) -> list[_Order]: ...
    def position(self, instrument_id: InstrumentId) -> _Position | None: ...
    def positions_open(self, *, instrument_id: InstrumentId | None = ...) -> list[_Position]: ...

class _Clock:
    def timestamp_ns(self) -> int: ...

class _Logger:
    def debug(self, message: str, *, color: object = ...) -> None: ...
    def error(self, message: str, *, color: object = ...) -> None: ...
    def info(self, message: str, *, color: object = ...) -> None: ...
    def warning(self, message: str, *, color: object = ...) -> None: ...

class _OrderFactory:
    def market(
        self,
        *,
        instrument_id: InstrumentId,
        order_side: OrderSide,
        quantity: Quantity,
        time_in_force: TimeInForce,
        reduce_only: bool = ...,
        tags: list[str] | None = ...,
    ) -> _Order: ...
    def limit(
        self,
        *,
        instrument_id: InstrumentId,
        order_side: OrderSide,
        quantity: Quantity,
        price: Price,
        time_in_force: TimeInForce,
        reduce_only: bool = ...,
        tags: list[str] | None = ...,
    ) -> _Order: ...
    def stop_market(
        self,
        *,
        instrument_id: InstrumentId,
        order_side: OrderSide,
        quantity: Quantity,
        trigger_price: Price,
        time_in_force: TimeInForce,
        reduce_only: bool = ...,
        tags: list[str] | None = ...,
    ) -> _Order: ...
    def trailing_stop_market(
        self,
        *,
        instrument_id: InstrumentId,
        order_side: OrderSide,
        quantity: Quantity,
        trailing_offset: Decimal,
        activation_price: Price,
        trigger_type: TriggerType,
        trailing_offset_type: TrailingOffsetType,
        time_in_force: TimeInForce,
        reduce_only: bool = ...,
        tags: list[str] | None = ...,
    ) -> _Order: ...

class _Portfolio:
    def account(self, venue: Venue) -> _Account | None: ...
    def equity(self, venue: Venue) -> Mapping[Currency, Money]: ...
    def missing_price_instruments(self, venue: Venue) -> set[InstrumentId]: ...

class Strategy:
    cache: _Cache
    clock: _Clock
    log: _Logger
    order_factory: _OrderFactory
    portfolio: _Portfolio
    # Neither `msgbus` nor `id` exists on 2.0's Strategy (measured against
    # nautilus_trader 2.0.0rc5): the message bus has no python surface, and the
    # identity attribute is `strategy_id`. Declaring them here would let code that
    # reads them type-check and then fail at runtime, which is how the last one
    # survived.
    strategy_id: object

    def __init__(self, config: StrategyConfig) -> None: ...
    def __init_subclass__(cls, **kwargs: object) -> None: ...
    def cancel_all_orders(self, instrument_id: InstrumentId) -> None: ...
    def cancel_order(self, order: _Order) -> None: ...
    def close_position(
        self,
        position: _Position,
        *,
        reduce_only: bool = ...,
        time_in_force: TimeInForce = ...,
    ) -> None: ...
    def pause(self) -> None: ...
    def register_indicator_for_bars(self, bar_type: BarType, indicator: object) -> None: ...
    def request_bars(self, bar_type: BarType, *, start: object = ...) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...
    def submit_order(self, order: _Order) -> None: ...
    def subscribe_bars(self, bar_type: BarType) -> None: ...
    def subscribe_quote_ticks(self, instrument_id: InstrumentId) -> None: ...
    def subscribe_trade_ticks(self, instrument_id: InstrumentId) -> None: ...
    def unsubscribe_bars(self, bar_type: BarType) -> None: ...
    def unsubscribe_quote_ticks(self, instrument_id: InstrumentId) -> None: ...
    def unsubscribe_trade_ticks(self, instrument_id: InstrumentId) -> None: ...
